

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function LocaleLayout({
  children,
  params: {locale}
}) {
  return (
    <html lang={locale}>
      <body>{children}</body>
    </html>
  );
}
